### ISSUE TITLE
Optuna v3.x.x no longer compatible with zombie trial cleaning

### ISSUE THREAD

**Issue by RandomDefaultUser** [mala-project/mala#497]
MALA implements a way to clean "zombie trials", i.e. trials which are not expected to finish anymore (e.g., because the original job broke). The API for this has changed from optuna v3 to v2, and this function no longer works. The regular MALA-optuna interface still works, but this particular part is currently not-functional. As it is important for extended, distributed hyperparameter optimization, I marked this as "critical". 
Fixing this should not be too hard.

**Comment by timcallow** [comment]
![Screenshot from 2024-01-12 14-52-39](https://github.com/mala-project/mala/assets/18050753/81999ae4-7e4d-4e0b-bad2-ed1430712ab5)

**Comment by elcorto** [comment]
In Optuna 3.x the API has [changed slightly](https://optuna.readthedocs.io/en/v3.6.1/reference/generated/optuna.storages.RDBStorage.html#optuna.storages.RDBStorage.set_trial_state_values):

`set_trial_state(trial_id, state)` -> `set_trial_state_values(trial_id, state, values=None)`

**Comment by elcorto** [comment]
To elaborate on the workflow:

MALA parallel Optuna is supposed to be used as described [in the Optuna docs](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html) -- just start the optimization script N times and let Optuna sync processes via a shared database, no MPI or anything. So we'd execute e.g. `examples/basic/ex04_hyperparameter_optimization.py` or `examples/advanced/ex05_checkpoint_hyperparameter_optimization.py` N times in parallel. On HPC, we can do so in a batch job such as this with N=12, where we use `mpirun` just to distribute Python processes across nodes:

```sh
#!/bin/bash
#SBATCH -N 3
#SBATCH --ntasks-per-node=4
#SBATCH --time=48:00:00
#SBATCH --job-name=HO
#SBATCH --gres=gpu:4
#SBATCH --mem=360G
#SBATCH -p some_ququw

module load ...
mpirun -np 12 python3 -u hyperopt01.py
```

Each of the 12 processes will run its own trials, on one GPU each. The batch will get killed after the designated runtime. Then unfinished trials will remain in the Optuna database in state RUNNING.

The current workflow for resuming the study which makes use of MALA's own resume tooling (see `examples/advanced/ex05_checkpoint_hyperparameter_optimization.py`) is this: before submitting the batch job again and let the script do the resume work, a user needs to modify the database like so:

```sh
python3 -c "import mala; mala.HyperOptOptuna.requeue_zombie_trials('hyperopt01', 'sqlite:///hyperopt.db')"
```

which will set the RUNNING trials to state WAITING. This is what the error
above shows.

If this works, the assumption is now that when Optuna resumes, it will pick up and re-run
those, before carrying on running the resumed study.

questions:

* Does "injecting" jobs like this disturb Optuna's operation in any way? In particular, since MALA pickle-dumps and re-loads the Optuna study object, is there state in that object and the database that must be in sync, i.e. do those trials *have* to be run? If not, then one could probably also delete them from the database (if that is the only source of truth for the study's state before we resume). In this case, the study will have missing data points from trials that have been suggested for a reason, so even if Optuna would resume fine, we may still want to re-run them from an optimization point of view.
* Optuna has some [resume functionality](https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/001_rdb.html), is this used in MALA? If not, could this help here?
