### ISSUE TITLE
Code duplications in `predictor.py`

### ISSUE THREAD

**Issue by elcorto** [mala-project/mala#508]
https://github.com/mala-project/mala/blob/9b0c4fc45dc93c9e7165302d9cb0d56eb1e5fb32/mala/network/predictor.py#L37-L40 in `__init__` is the same as https://github.com/mala-project/mala/blob/9b0c4fc45dc93c9e7165302d9cb0d56eb1e5fb32/mala/network/predictor.py#L65-L68 in `predict_from_qeout()`. Since the former is in the constructor, I think the latter can be skipped.

Also here https://github.com/mala-project/mala/blob/9b0c4fc45dc93c9e7165302d9cb0d56eb1e5fb32/mala/network/predictor.py#L105-L110 `self.data.grid_dimension = self.parameters.inference_data_grid` is already performed in `__init__` so the check could be changed to something like

```py
if np.prod(self.parameters.inference_data_grid) == 0:
    ... code from else clause here ...
```

Note: `<= 0` would be correct but I gess `np.prod(self.parameters.inference_data_grid)` is never < 0.

**Comment by RandomDefaultUser** [comment]
Hi @elcorto thanks for bringing this to my attention, I will have a look! :)

**Comment by RandomDefaultUser** [comment]
I looked into the second part of this issue, and do no longer think this part of the code is redundant. The additional check makes sure that if the user specified an inference grid AFTER loading of the predictor class, this change is taken into account. Since the predictor object is loaded and the parameters object is not created beforehand, if you want to use a different inference grid this is the only way (I think?).

The first part is fixed by https://github.com/mala-project/mala/pull/562, so I am closing this issue.
